/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CalendarConflict = IDL.Record({
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'time' : IDL.Text,
});
export const RiskSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const RiskItem = IDL.Record({
  'source' : IDL.Text,
  'text' : IDL.Text,
  'severity' : RiskSeverity,
});
export const RevenuePulse = IDL.Record({
  'mrr' : IDL.Nat,
  'topCustomer' : IDL.Text,
  'mrrChange' : IDL.Int,
  'churnRate' : IDL.Float64,
});
export const WarRoomBriefing = IDL.Record({
  'calendarConflicts' : IDL.Vec(CalendarConflict),
  'topRisks' : IDL.Vec(RiskItem),
  'uncomfortableQuestion' : IDL.Text,
  'revenuePulse' : RevenuePulse,
});
export const DecisionUrgency = IDL.Variant({
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DecisionSource = IDL.Variant({
  'slack' : IDL.Null,
  'gmail' : IDL.Null,
});
export const Decision = IDL.Record({
  'id' : IDL.Nat,
  'draftReply' : IDL.Text,
  'urgency' : DecisionUrgency,
  'subject' : IDL.Text,
  'source' : DecisionSource,
  'snippet' : IDL.Text,
  'sender' : IDL.Text,
  'senderAvatar' : IDL.Text,
});
export const MeetingToDecline = IDL.Record({
  'title' : IDL.Text,
  'time' : IDL.Text,
  'attendees' : IDL.Vec(IDL.Text),
  'declineMessage' : IDL.Text,
});
export const FocusMode = IDL.Record({
  'blockEnd' : IDL.Text,
  'meetingsToDecline' : IDL.Vec(MeetingToDecline),
  'blockStart' : IDL.Text,
  'enabled' : IDL.Bool,
  'priority' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBriefing' : IDL.Func([], [WarRoomBriefing], ['query']),
  'getDecisions' : IDL.Func([], [IDL.Vec(Decision)], ['query']),
  'getFocusMode' : IDL.Func([], [FocusMode], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CalendarConflict = IDL.Record({
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'time' : IDL.Text,
  });
  const RiskSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RiskItem = IDL.Record({
    'source' : IDL.Text,
    'text' : IDL.Text,
    'severity' : RiskSeverity,
  });
  const RevenuePulse = IDL.Record({
    'mrr' : IDL.Nat,
    'topCustomer' : IDL.Text,
    'mrrChange' : IDL.Int,
    'churnRate' : IDL.Float64,
  });
  const WarRoomBriefing = IDL.Record({
    'calendarConflicts' : IDL.Vec(CalendarConflict),
    'topRisks' : IDL.Vec(RiskItem),
    'uncomfortableQuestion' : IDL.Text,
    'revenuePulse' : RevenuePulse,
  });
  const DecisionUrgency = IDL.Variant({
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DecisionSource = IDL.Variant({
    'slack' : IDL.Null,
    'gmail' : IDL.Null,
  });
  const Decision = IDL.Record({
    'id' : IDL.Nat,
    'draftReply' : IDL.Text,
    'urgency' : DecisionUrgency,
    'subject' : IDL.Text,
    'source' : DecisionSource,
    'snippet' : IDL.Text,
    'sender' : IDL.Text,
    'senderAvatar' : IDL.Text,
  });
  const MeetingToDecline = IDL.Record({
    'title' : IDL.Text,
    'time' : IDL.Text,
    'attendees' : IDL.Vec(IDL.Text),
    'declineMessage' : IDL.Text,
  });
  const FocusMode = IDL.Record({
    'blockEnd' : IDL.Text,
    'meetingsToDecline' : IDL.Vec(MeetingToDecline),
    'blockStart' : IDL.Text,
    'enabled' : IDL.Bool,
    'priority' : IDL.Text,
  });
  
  return IDL.Service({
    'getBriefing' : IDL.Func([], [WarRoomBriefing], ['query']),
    'getDecisions' : IDL.Func([], [IDL.Vec(Decision)], ['query']),
    'getFocusMode' : IDL.Func([], [FocusMode], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };