/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarConflict {
  'title' : string,
  'participants' : Array<string>,
  'time' : string,
}
export interface Decision {
  'id' : bigint,
  'draftReply' : string,
  'urgency' : DecisionUrgency,
  'subject' : string,
  'source' : DecisionSource,
  'snippet' : string,
  'sender' : string,
  'senderAvatar' : string,
}
export type DecisionSource = { 'slack' : null } |
  { 'gmail' : null };
export type DecisionUrgency = { 'high' : null } |
  { 'medium' : null };
export interface FocusMode {
  'blockEnd' : string,
  'meetingsToDecline' : Array<MeetingToDecline>,
  'blockStart' : string,
  'enabled' : boolean,
  'priority' : string,
}
export interface MeetingToDecline {
  'title' : string,
  'time' : string,
  'attendees' : Array<string>,
  'declineMessage' : string,
}
export interface RevenuePulse {
  'mrr' : bigint,
  'topCustomer' : string,
  'mrrChange' : bigint,
  'churnRate' : number,
}
export interface RiskItem {
  'source' : string,
  'text' : string,
  'severity' : RiskSeverity,
}
export type RiskSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface WarRoomBriefing {
  'calendarConflicts' : Array<CalendarConflict>,
  'topRisks' : Array<RiskItem>,
  'uncomfortableQuestion' : string,
  'revenuePulse' : RevenuePulse,
}
export interface _SERVICE {
  'getBriefing' : ActorMethod<[], WarRoomBriefing>,
  'getDecisions' : ActorMethod<[], Array<Decision>>,
  'getFocusMode' : ActorMethod<[], FocusMode>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];