/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CalendarConflict {
    title: string;
    participants: Array<string>;
    time: string;
}
export interface RiskItem {
    source: string;
    text: string;
    severity: RiskSeverity;
}
export interface FocusMode {
    blockEnd: string;
    meetingsToDecline: Array<MeetingToDecline>;
    blockStart: string;
    enabled: boolean;
    priority: string;
}
export interface Decision {
    id: bigint;
    draftReply: string;
    urgency: DecisionUrgency;
    subject: string;
    source: DecisionSource;
    snippet: string;
    sender: string;
    senderAvatar: string;
}
export interface WarRoomBriefing {
    calendarConflicts: Array<CalendarConflict>;
    topRisks: Array<RiskItem>;
    uncomfortableQuestion: string;
    revenuePulse: RevenuePulse;
}
export interface RevenuePulse {
    mrr: bigint;
    topCustomer: string;
    mrrChange: bigint;
    churnRate: number;
}
export interface MeetingToDecline {
    title: string;
    time: string;
    attendees: Array<string>;
    declineMessage: string;
}
export enum DecisionSource {
    slack = "slack",
    gmail = "gmail"
}
export enum DecisionUrgency {
    high = "high",
    medium = "medium"
}
export enum RiskSeverity {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    getBriefing(): Promise<WarRoomBriefing>;
    getDecisions(): Promise<Array<Decision>>;
    getFocusMode(): Promise<FocusMode>;
}
import type { CalendarConflict as _CalendarConflict, Decision as _Decision, DecisionSource as _DecisionSource, DecisionUrgency as _DecisionUrgency, RevenuePulse as _RevenuePulse, RiskItem as _RiskItem, RiskSeverity as _RiskSeverity, WarRoomBriefing as _WarRoomBriefing } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getBriefing(): Promise<WarRoomBriefing> {
        if (this.processError) {
            try {
                const result = await this.actor.getBriefing();
                return from_candid_WarRoomBriefing_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBriefing();
            return from_candid_WarRoomBriefing_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDecisions(): Promise<Array<Decision>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecisions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecisions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFocusMode(): Promise<FocusMode> {
        if (this.processError) {
            try {
                const result = await this.actor.getFocusMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFocusMode();
            return result;
        }
    }
}
function from_candid_DecisionSource_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DecisionSource): DecisionSource {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DecisionUrgency_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DecisionUrgency): DecisionUrgency {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Decision_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Decision): Decision {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RiskItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskItem): RiskItem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RiskSeverity_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskSeverity): RiskSeverity {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_WarRoomBriefing_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WarRoomBriefing): WarRoomBriefing {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    draftReply: string;
    urgency: _DecisionUrgency;
    subject: string;
    source: _DecisionSource;
    snippet: string;
    sender: string;
    senderAvatar: string;
}): {
    id: bigint;
    draftReply: string;
    urgency: DecisionUrgency;
    subject: string;
    source: DecisionSource;
    snippet: string;
    sender: string;
    senderAvatar: string;
} {
    return {
        id: value.id,
        draftReply: value.draftReply,
        urgency: from_candid_DecisionUrgency_n11(_uploadFile, _downloadFile, value.urgency),
        subject: value.subject,
        source: from_candid_DecisionSource_n13(_uploadFile, _downloadFile, value.source),
        snippet: value.snippet,
        sender: value.sender,
        senderAvatar: value.senderAvatar
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    calendarConflicts: Array<_CalendarConflict>;
    topRisks: Array<_RiskItem>;
    uncomfortableQuestion: string;
    revenuePulse: _RevenuePulse;
}): {
    calendarConflicts: Array<CalendarConflict>;
    topRisks: Array<RiskItem>;
    uncomfortableQuestion: string;
    revenuePulse: RevenuePulse;
} {
    return {
        calendarConflicts: value.calendarConflicts,
        topRisks: from_candid_vec_n3(_uploadFile, _downloadFile, value.topRisks),
        uncomfortableQuestion: value.uncomfortableQuestion,
        revenuePulse: value.revenuePulse
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: string;
    text: string;
    severity: _RiskSeverity;
}): {
    source: string;
    text: string;
    severity: RiskSeverity;
} {
    return {
        source: value.source,
        text: value.text,
        severity: from_candid_RiskSeverity_n6(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    high: null;
} | {
    medium: null;
}): DecisionUrgency {
    return "high" in value ? DecisionUrgency.high : "medium" in value ? DecisionUrgency.medium : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    slack: null;
} | {
    gmail: null;
}): DecisionSource {
    return "slack" in value ? DecisionSource.slack : "gmail" in value ? DecisionSource.gmail : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskSeverity {
    return "low" in value ? RiskSeverity.low : "high" in value ? RiskSeverity.high : "medium" in value ? RiskSeverity.medium : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiskItem>): Array<RiskItem> {
    return value.map((x)=>from_candid_RiskItem_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Decision>): Array<Decision> {
    return value.map((x)=>from_candid_Decision_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
